### ISSUE TITLE
Link to https://popfactfinder.planning.nyc.gov/ is broken

### ISSUE THREAD

**Issue by nrjones8** [NYCPlanning/labs-home#48]
#### Description
https://planninglabs.nyc/projects/population-fact-finder/ links to https://popfactfinder.planning.nyc.gov/

but https://popfactfinder.planning.nyc.gov/ times out with a 502 after failing to load for a bit.

#### What should happen:
A user should be able to view the population fact finder!

#### What happened instead:
it 502'd

#### How to reproduce this bug:
See above (https://popfactfinder.planning.nyc.gov/ times out, and it's linked to from https://planninglabs.nyc/projects/population-fact-finder/)

#### Browser(s) and Device(s) observed on:
Chrome, macbook

#### Screenshot
<img width="894" alt="screen shot 2019-02-09 at 3 09 45 pm" src="https://user-images.githubusercontent.com/503781/52525791-d2759980-2c7c-11e9-9b29-ab7b02c1fc82.png">

**Comment by hannahkates** [comment]
Hi @nrjones8, thanks for reporting this. It appears that Population FactFinder was down for a few hours on Saturday when you tried to use it. We're investigating why this happened, but the site is up and running again now.

**Comment by nrjones8** [comment]
Oh great, nevermind then - thanks for the quick follow up!
